apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    upstream backend {
        server app-1-svc:80;
        server app-2-svc:80;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
